---
ec2_image: shared-dbproxy-1.3.0-x86_64
ecr_image: 415983589830.dkr.ecr.eu-west-1.amazonaws.com/shared-dbproxy:1.3.0 #should be the same as ec2_image version
Service: "dbproxy"
grafana_systest_ip: "108.128.215.206/32"
grafana_prod_ip: "63.34.170.224/32"
grafana_new_prod_ip: 34.251.220.227/32 #new prod instance
minimum_instances: 1
maximum_instances: 1
provision_pv: "true"
instance_type: "t3.small"
warn_high_cpu_percent: "70"
alarm_high_cpu_percent: "90"
fw_ports_input: "5432"
fw_ports_output: "5432"
pv_mount: "/data"
